### ISSUE TITLE
Migrate to using Whitelist submodule

### ISSUE THREAD

**Issue by EGreg** [Intercoin/FundContract#13]
The Whitelist code has `whitelisted` function which you can use everywhere:

```
if (!whitelisted) {
   revert NotInWhitelist();
}
```

it will take care of the rest by itself. Just make sure that init params also include `Whitelist whitelist` at the end, allowing the user to indicate a nonzero whitelist struct.

**Comment by artman325** [comment]
using whitelist code in repo 
https://github.com/Intercoin/Whitelist

also periodic commint will pushed as npm package 
see https://www.npmjs.com/package/@artman325/whitelist
