### ISSUE TITLE
Price should depend on total bought

### ISSUE THREAD

**Issue by artman325** [Intercoin/FundContract#17]
now we have two params `_timestamps` and `_prices`. price depend of time.
for example:
```
_timestamps = [1 May, 1 June, 1August]
_prices = [10¢, 50¢, $2]
```
So from 1 May price will be 10¢, from 1 June - 50¢, and after 1August = $2 respectively.

**What's need to do**
price should depend on total bought, overwise should be stayed as it was, so need to add another parameter like `amountRaised`
for example:
```
amountRaised = [0,100,200]  // first amount should be zero for better understand
```
- if 5May -was bought 110 tokens, Price should be 50¢, instead of 10¢
- if 10May -was bought 250 tokens, Price should be $2, instead of 10¢
- if 15June -was bought 260 tokens, Price should be $2, instead of 50¢
Also 
- if 5May -was bought 10 tokens, Price should be 10¢
- if 5June -was bought 20 tokens, Price should be 50¢
- if 5August -was bought 150 tokens, Price should be $2
And so on. 

**Summary**
Need to get a maximum price from _prices[periodFromTime] and _prices[periodFromAmountRaised]

**Comment by EGreg** [comment]
Please also switch from timestamps to durations, so that durations start from start time of each level, whether the contract switched to it because of total tokens sold, or because previous duration ended.
